import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { Header } from "@/components/elements/Header";
import { Sidebar } from "@/components/elements/Sidebar";
import { Footer } from "@/components/elements/Footer";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen`}
			>
				<div className="container h-full">
					<Header />

					<div className="flex h-[calc(100%-100px)]">
						
						<Sidebar />

						<div className="w-[calc(100%-250px-1rem)] bg-bg-2 rounded-r-xl">
							{children}
						</div>
					</div>

					<Footer />
				</div>
			</body>
		</html>
	);
}
